### ISSUE TITLE
Messy meetings directory

### ISSUE THREAD

**Issue by vanDeventer** [ojaohe-3/d0020e#36]
Hi,

There is a bunch of files in the Meetings directory or folder. It is hard to know which file one might want to look at. You either should name the files in a good order fashion or in the README file, you link a list of meetings (e.g., like a table of content).

Best,

Jan

**Comment by ojaohe-3** [comment]
Have implemented a fix, awating approval, or fix later

**Comment by vanDeventer** [comment]
Good job. I find it much better to find the history of meeting. Thank you
